wandb_version: 1

beta-kl:
  value: 0
data-path:
  value: ../data/unbalanced/
epochs:
  value: 30
fix-decoders:
  value: true
latent-dim:
  value: 5
model:
  value: jnf_mnist_fashion
obj:
  value: jmvae_nf
skip-warmup:
  value: true
warmup:
  value: 15
