wandb_version: 1

K:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: epoch
      6:
      - 3
    - 1: neg_entropy
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png._type
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png.sha256
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png.size
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png.path
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png.format
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png.width
      5: 1
      6:
      - 1
    - 1: cond_samples_0x0\.png.height
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png._type
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png.sha256
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png.size
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png.path
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png.format
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png.width
      5: 1
      6:
      - 1
    - 1: cond_samples_0x1\.png.height
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png._type
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png.sha256
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png.size
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png.path
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png.format
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png.width
      5: 1
      6:
      - 1
    - 1: cond_samples_1x0\.png.height
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png._type
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png.sha256
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png.size
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png.path
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png.format
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png.width
      5: 1
      6:
      - 1
    - 1: cond_samples_1x1\.png.height
      5: 1
      6:
      - 1
    - 1: joint_embedding._type
      5: 1
      6:
      - 1
    - 1: joint_embedding.sha256
      5: 1
      6:
      - 1
    - 1: joint_embedding.size
      5: 1
      6:
      - 1
    - 1: joint_embedding.path
      5: 1
      6:
      - 1
    - 1: joint_embedding.format
      5: 1
      6:
      - 1
    - 1: joint_embedding.width
      5: 1
      6:
      - 1
    - 1: joint_embedding.height
      5: 1
      6:
      - 1
    - 1: uni_embedding._type
      5: 1
      6:
      - 1
    - 1: uni_embedding.sha256
      5: 1
      6:
      - 1
    - 1: uni_embedding.size
      5: 1
      6:
      - 1
    - 1: uni_embedding.path
      5: 1
      6:
      - 1
    - 1: uni_embedding.format
      5: 1
      6:
      - 1
    - 1: uni_embedding.width
      5: 1
      6:
      - 1
    - 1: uni_embedding.height
      5: 1
      6:
      - 1
    - 1: sample_posteriors._type
      5: 1
      6:
      - 1
    - 1: sample_posteriors.sha256
      5: 1
      6:
      - 1
    - 1: sample_posteriors.size
      5: 1
      6:
      - 1
    - 1: sample_posteriors.path
      5: 1
      6:
      - 1
    - 1: sample_posteriors.format
      5: 1
      6:
      - 1
    - 1: sample_posteriors.width
      5: 1
      6:
      - 1
    - 1: sample_posteriors.height
      5: 1
      6:
      - 1
    - 1: generate_joint._type
      5: 1
      6:
      - 1
    - 1: generate_joint.sha256
      5: 1
      6:
      - 1
    - 1: generate_joint.size
      5: 1
      6:
      - 1
    - 1: generate_joint.path
      5: 1
      6:
      - 1
    - 1: generate_joint.format
      5: 1
      6:
      - 1
    - 1: generate_joint.width
      5: 1
      6:
      - 1
    - 1: generate_joint.height
      5: 1
      6:
      - 1
    - 1: gen_from_cond_0._type
      5: 1
      6:
      - 1
    - 1: gen_from_cond_0.sha256
      5: 1
      6:
      - 1
    - 1: gen_from_cond_0.size
      5: 1
      6:
      - 1
    - 1: gen_from_cond_0.path
      5: 1
      6:
      - 1
    - 1: gen_from_cond_0.format
      5: 1
      6:
      - 1
    - 1: gen_from_cond_0.width
      5: 1
      6:
      - 1
    - 1: gen_from_cond_0.height
      5: 1
      6:
      - 1
    - 1: gen_from_cond_1._type
      5: 1
      6:
      - 1
    - 1: gen_from_cond_1.sha256
      5: 1
      6:
      - 1
    - 1: gen_from_cond_1.size
      5: 1
      6:
      - 1
    - 1: gen_from_cond_1.path
      5: 1
      6:
      - 1
    - 1: gen_from_cond_1.format
      5: 1
      6:
      - 1
    - 1: gen_from_cond_1.width
      5: 1
      6:
      - 1
    - 1: gen_from_cond_1.height
      5: 1
      6:
      - 1
    - 1: test_loss
      5: 1
      6:
      - 1
    - 1: histograms._type
      5: 1
      6:
      - 1
    - 1: histograms.sha256
      5: 1
      6:
      - 1
    - 1: histograms.size
      5: 1
      6:
      - 1
    - 1: histograms.path
      5: 1
      6:
      - 1
    - 1: histograms.format
      5: 1
      6:
      - 1
    - 1: histograms.width
      5: 1
      6:
      - 1
    - 1: histograms.height
      5: 1
      6:
      - 1
    python_version: 3.6.8
    start_time: 1656689315
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      3:
      - 7
      - 16
      4: 3.6.8
      5: 0.12.17
      8:
      - 5
batch_size:
  desc: null
  value: 256
beta_kl:
  desc: null
  value: 1
beta_prior:
  desc: null
  value: 1
data_path:
  desc: null
  value: ../data/circles_squares/
decrease_beta_kl:
  desc: null
  value: 1
dist:
  desc: null
  value: laplace
epochs:
  desc: null
  value: 30
eval_mode:
  desc: null
  value: false
experiment:
  desc: null
  value: jmvae
fix_decoders:
  desc: null
  value: true
fix_jencoder:
  desc: null
  value: true
freq_analytics:
  desc: null
  value: 5
latent_dim:
  desc: null
  value: 2
learn_prior:
  desc: null
  value: false
llik_scaling:
  desc: null
  value: 0.0
logp:
  desc: null
  value: false
looser:
  desc: null
  value: false
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: circles_squares
no_analytics:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
no_nf:
  desc: null
  value: false
no_recon:
  desc: null
  value: false
num_hidden_layers:
  desc: null
  value: 1
obj:
  desc: null
  value: dreg
print_freq:
  desc: null
  value: 0
seed:
  desc: null
  value: 1
skip_warmup:
  desc: null
  value: false
use_pretrain:
  desc: null
  value: ''
warmup:
  desc: null
  value: 0
