wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
    start_time: 1661339040
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      3:
      - 16
      4: 3.6.10
      5: 0.12.17
      8:
      - 5
lr:
  desc: null
  value: 0.0001
n_epochs:
  desc: null
  value: 100
