wandb_version: 1

beta-kl:
  value: 0.001864612512065822
data-path:
  value: ../data/unbalanced/
decrease_beta_kl:
  value: 0.9567544628818436
epochs:
  value: 30
fix-decoders:
  value: true
latent-dim:
  value: 5
model:
  value: jnf_mnist_fashion
obj:
  value: jmvae_nf
skip-warmup:
  value: true
warmup:
  value: 15
