wandb_version: 1

K:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: epoch
      6:
      - 3
    python_version: 3.6.8
    start_time: 1655716743
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      3:
      - 7
      4: 3.6.8
      5: 0.12.17
      8:
      - 5
batch_size:
  desc: null
  value: 256
beta:
  desc: null
  value: 1000
beta_prior:
  desc: null
  value: 1
beta_rec:
  desc: null
  value: 0.3
data_path:
  desc: null
  value: ../data/
dist:
  desc: null
  value: normal
epochs:
  desc: null
  value: 30
experiment:
  desc: null
  value: ''
fix_decoders:
  desc: null
  value: false
fix_jencoder:
  desc: null
  value: true
latent_dim:
  desc: null
  value: 20
learn_prior:
  desc: null
  value: false
llik_scaling:
  desc: null
  value: 0.0
logp:
  desc: null
  value: false
looser:
  desc: null
  value: false
model:
  desc: null
  value: mnist_svhn
no_analytics:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
no_nf:
  desc: null
  value: true
num_hidden_layers:
  desc: null
  value: 1
obj:
  desc: null
  value: dreg
pre_trained:
  desc: null
  value: ''
print_freq:
  desc: null
  value: 0
seed:
  desc: null
  value: 1
warmup:
  desc: null
  value: 0
