wandb_version: 1

K:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: epoch
      6:
      - 3
    python_version: 3.6.8
    start_time: 1655996797
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      3:
      - 7
      - 16
      4: 3.6.8
      5: 0.12.17
      8:
      - 5
batch_size:
  desc: null
  value: 256
beta:
  desc: null
  value: 1.0
beta_prior:
  desc: null
  value: 0.5
beta_rec:
  desc: null
  value: 1.0
data_path:
  desc: null
  value: ../data/empty_full_bk/
dist:
  desc: null
  value: normal
epochs:
  desc: null
  value: 60
experiment:
  desc: null
  value: empty_full
fix_decoders:
  desc: null
  value: true
fix_jencoder:
  desc: null
  value: true
latent_dim:
  desc: null
  value: 2
learn_prior:
  desc: null
  value: false
llik_scaling:
  desc: null
  value: 0.0
logp:
  desc: null
  value: false
looser:
  desc: null
  value: false
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: jnf_circles_squares
no_analytics:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
no_nf:
  desc: null
  value: true
num_hidden_layers:
  desc: null
  value: 1
obj:
  desc: null
  value: jmvae_nf
pre_trained:
  desc: null
  value: ''
print_freq:
  desc: null
  value: 0
seed:
  desc: null
  value: 1
skip_warmup:
  desc: null
  value: false
warmup:
  desc: null
  value: 30
